[package]
name = "nll-repr"
version = "0.1.0"
license = "Apache-2.0/MIT"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
build = "build.rs"

[dependencies]
lalrpop-intern = "0.12.4"
lalrpop-util = "0.12.4"
lalrpop = "0.12.4"
typed-arena = "1.1.0"

[build-dependencies]
lalrpop = "0.12.4"