[package]
name = "nll"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]

[dependencies]
docopt = "0.6"
lalrpop-intern = "0.11.0"
nll-repr = { path = "../nll-repr" }
rustc-serialize = "0.3"
graph-algorithms = { path = "../graph-algorithms" }